# 389. Find the Difference
#
# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.
#
# Example:
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.


from collections import Counter


class Solution(object):
    def findTheDifference(self, s, t):

        cs = Counter(s)
        ct = Counter(t)
        result = ""

        for m in ct:
            if m not in cs:
                for x in range(ct[m]):
                    result += m
            else:
                if ct[m] > cs[m]:
                    for x in range(ct[m] - cs[m]):
                        result += m

        return result
